set shell := ["zsh", "-cu"]

default:
    just check

fmt:
    cargo fmt

fmt-check:
    cargo fmt --check

clippy:
    cargo clippy --all-targets -- -D warnings

test:
    cargo test

check: fmt-check clippy test

build:
    cargo build --release --bin rsymphony

alias b := build

run workflow="./WORKFLOW.md" config="./.symphony.toml":
    cargo run --bin rsymphony -- --i-understand-that-this-will-be-running-without-the-usual-guardrails --config {{config}} {{workflow}}

validate workflow="./WORKFLOW.md" config="./.symphony.toml":
    cargo run --bin rsymphony -- --config {{config}} validate {{workflow}}

install:
    cargo install --path . --bin rsymphony --force

alias i := install

uninstall:
    cargo uninstall rsymphony

alias u := uninstall
